# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Bellows.Bellows
PackageVersion: 1.13.0
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
ReleaseDate: 2026-10-02
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/bellowsai/bellows-releases/releases/download/v1.13.0/Bellows-1.13.0-setup.exe
  InstallerSha256: 509F95275C5AEAD3C6260F05D06F643C3357F30D86E803153E871DA8CB08FEE4
ManifestType: installer
ManifestVersion: 1.12.0
