# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Bellows.Bellows
PackageVersion: 1.15.3
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
ReleaseDate: 2026-10-06
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/bellowsai/bellows-releases/releases/download/v1.15.3/Bellows-1.15.3-setup.exe
  InstallerSha256: D4080B8706E289EF86BA884F9DE8B9BCE716CB0D43AE2BF2BF89D243553F2159
ManifestType: installer
ManifestVersion: 1.12.0
